config/routes.rb
Rails.application.routes.draw do

    # 顧客用
  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
   devise_for :admin, skip: [:registrations, :passwords], controllers:{
  sessions: "admin/sessions"
   }

  # 顧客のルーティング
  scope module: :public do
    root to: 'homes#top'

    get '/about' =>'homes#about'
    get '/customers/show' =>'customers#show'
    get '/customers/infomation/edit' =>'customers#edit'
    patch '/customers/infomation' =>'customers#update'
    get '/customers/withdraw_check' =>'customers#withdraw_check'
    patch  '/customers/withdraw' =>'customers#withdraw'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/conplete' => 'orders#complete'

    resources :items, only:[:index,:show]
    resources :cart_items, only:[:index,:create,:destroy]
    resources :orders, only:[:index,:show,:new,:create]
  end

   # 管理者側のルーティング設定
  namespace :admin do
  resources :genres ,only:[:create,:update,:edit,:index]
  resources :items , only:[:create,:update,:edit,:index,:new,:show]
  resources :customers , only:[:update,:edit,:index,:show]
  resources :orders , only:[:index,:show]
  end


end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items , dependent: :destroy
  has_many :orders, dependent: :destroy

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + first_name + last_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items , dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_products, dependent: :destroy

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {
    credit: 1, #クレジットカード
    bank: 2, #銀行振込
  }

  has_many :order_products, dependent: :destroy
  belongs_to :customer
   def with_tax_price
    (price * 1.1).floor
   end

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def sabtotal
    (unit_price*1.1).floor * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    # ジャンル一覧の表示
    @genres =Genre.all
  end

  def create
    @genre =Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path

  end

  # 対象ジャンルの編集が押されたときの処理
  def edit
    @genre= Genre.find(params[:id])
  end

  def update
    @genre= Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end



  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    # 商品一覧
    @items=Item.all
  end

  def new
    # 商品新規登録画面
    @item = Item.new
  end

  def create
    # 新規登録の処理
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    # 商品情報の詳細画面
    @item = Item.find(params[:id])
  end

  def edit
    # 商品情報の編集
    @item = Item.find{params[:id]}
  end

  def update
    @item= Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end


  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price,:image,:genre_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  # 注文履歴一覧ページ
  def index
    @order = Order.all
  end

  # 注文履歴の詳細
  def show
    # 商品合計の金額用の変数を初期化
    @total = 0
    # クリックした注文情報を取得
    @order = Order.find(params[:id])
    @order.shipping_fee =800
    # クリックされた注文情報の商品情報を取得
    @order_item = @order.order_products
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
 def after_sign_in_path_for(resource)
   admin_orders_path
 end

 def after_sign_out_path_for(resource)
    admin_session_path
 end


end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/admin/genres/edit.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

 <body>
   <div class="container">
       <div class="row">
        <div class="mx-auto">
          <h1>ジャンル編集</h1>
          <%= form_with model: @genre,url: admin_genre_path, method: :PATCH do |f| %>
          <div>ジャンル名 <%=f.text_field :name%>
          <%= f.submit "編集内容を保存" %></div>
          <% end %>
         </div>
       </div>
    </div>
 </body>
 </html>

app/views/admin/genres/index.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

 <body>
   <div class="container">
       <div class="row">
        <div class="mx-auto">
          <h1>ジャンル一覧・追加</h1>
          <%= form_with model: @genre,url: admin_genres_path, method: :post do |f| %>
          <div class="janre">ジャンル名 <%= f.text_field :name%>   <%=f.submit '新規登録',class: 'btn btn-success'%></div>
          <% end %>

          <table class="table">
            <!--テーブルヘッダ-->
            <thead>
              <tr><th>ジャンル</th>
                  <th></th>
              </tr>
            </thead>
            <!--テーブルの項目設定-->
           <% @genres.each do |g|%>
           <tbody>
             <tr>
               <td><%=g.name%></td>
               <td><%=link_to '編集する' ,edit_admin_genre_path(g.id),class: 'btn btn-success'%></td>
             </tr>
           </tbody>
           <% end %>
           </table>
         </div>
       </div>
    </div>
 </body>
 </html>

app/views/admin/items/edit.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

 <body>
   <main>
    <div class="container">
      <div class="row">
        <div class="mx-auto">
          <h1>商品編集</h1>
            <%= form_with model: @item ,url: admin_item_path, method: :PATCH do |f| %>
            <div class="product">商品画像<%= f.file_field :image, accept: "image/*" %></div>
            <div class="product">商品名<%= f.text_field :name%></div>
            <div class="product">商品説明 <%= f.text_area :introduction%></div>
            <div class="product">ジャンル<%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></div>
            <div class="product">税抜き価格<%= f.text_field :price%></div>
            <%= f.submit "変更を保存" %>
            <% end %>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/admin/items/index.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

 <body>
   <div class="container">
       <div class="row">
        <div class="mx-auto">
          <h1>商品一覧</h1>
          <table class="table">
            <!--テーブルヘッダ-->
            <thead>
              <tr>
                <th>商品ID</th>
                <th>商品名</th>
                <th>税抜き価格</th>
                <th>ジャンル</th>
              </tr>
            </thead>
            <!--テーブルの項目設定-->
           <% @items.each do |item| %>
           <tbody>
             <tr>
               <td><div><%= item.id%></div></td>
               <td><div><%= link_to admin_item_path(item.id) do %><%=item.name%><% end %></div></td>
               <td><div><%= item.price%></div></td>
               <td><div><%= item.genre.name%></div></td>
               <% end %>
             </tr>
           </tbody>
           </table>
           <%=link_to '新規登録' ,new_admin_item_path,class: 'btn btn-success'%>
         </div>
       </div>
    </div>
 </body>

 </html>

app/views/admin/items/new.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

 <body>
   <main>
     <%= form_with model: @item ,url: admin_items_path, method: :POST do |f| %>
     <form class="form-horizontal">
              <div class="form-group row my-3">
               <label class="col-sm-4"><h1>商品新規登録</h1></label>
              </div>

              <div class="form-group row my-3">
                <label class="col-sm-4">商品画像</label>
                 <dd><label class="col-sm-4"><%= f.file_field :image, accept: "image/*" %></label></dd>
              </div>

              <div class="form-group row my-3">
                <label class="col-sm-4">商品名</label>
                 <dd><label class="col-sm-4"><%= f.text_field :name, placeholder: "商品名"  %></label></dd>
              </div>

              <div class="form-group row my-3">
                <label class="col-sm-4">商品説明</label>
                 <dd><label class="col-sm-4"><%= f.text_area :introduction,placeholder: "ここに説明文を記述します" %></label></dd>
              </div>

              <div class="form-group row my-3">
                <label class="col-sm-4">ジャンル</label>
                 <dd><label class="col-sm-4"><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></label></dd>
              </div>

              <div class="form-group row my-3">
                <label class="col-sm-4">税抜き価格</label>
                 <dd><label class="col-sm-4"><%= f.text_field :price,placeholder: "1000"%></label></dd>
              </div>

              <div class="form-group row my-3">
                <label class="col-sm-4"><%= f.submit "新規登録" ,class: 'btn btn-success btn-lg '%></label>
              </div>
      <% end %>
    </main>
  </body>
</html>

app/views/admin/items/show.html.erb
<html>
  <head>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>
  <body>
    <h1>商品詳細</h1>
    <div class="container">
       <div class="row">
        <div class="col-md-3">
          <%= image_tag @item.get_image(100,100) %>
        </div>

        <div class="col-md-8 offset-md-1">
          <div>商品名:<%=@item.name%></div>
          <div>商品説明:<%=@item.introduction%></div>
          <div>ジャンル:<%=@item.genre.name%></div>
          <div>税込み価格(税抜き価格):<%=@item.with_tax_price%>(<%=@item.price%>)円</div>
          <div><%= link_to "編集する",edit_admin_item_path(@item.id),class: 'btn btn-success'%></div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/admin/orders/index.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

 <body>
   <div class="container">
       <div class="row">
        <div class="mx-auto">
          <h1>注文履歴一覧</h1>
          <table class="table">
            <!--テーブルヘッダ-->
            <thead>
              <tr>
                <th>購入日時</th>
                <th>購入者</th>
                <th>注文個数</th>

              </tr>
            </thead>
            <!--テーブルの項目設定-->
           <% @order.each do |c| %>
           <tbody>
             <tr>
               <td><div><%= link_to admin_order_path(c.id) do %><%= c.updated_at.to_s(:datetime_jp)%><% end %></div></td>
               <td><div><%=c.customer.first_name%><%=c.customer.last_name%></div></td>
               <td><div><%= c.order_products.sum(:amount) %></div></td>
               <% end %>
             </tr>
           </tbody>
           </table>
         </div>
       </div>
    </div>
 </body>
 </html>

app/views/admin/orders/show.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

 <body>
   <div class="container">
       <div class="row">
        <div class="col-8">
          <h1>注文履歴詳細</h1>
            <div>購入者：      <%= @order.customer.first_name%><%= @order.customer.last_name%></div>
            <div>注文日：      <%= @order.updated_at.to_s(:datetime_jp)%></div>
            <div>配送先：      <%= @order.address%>   <%= @order.adress_name%></div>
            <div>支払方法：
            <% if @order.payment_method == "creait"%>
              クレジットカード
            <% else %>
              銀行振込
            <% end %>
            </div>
            <table class="table">
            <!--商品情報の作成-->
             <thead>
              <tr>
                <th>商品名</th>
                <th>単価(税込み)</th>
                <th>数量</th>
                <th>小計</th>
              </tr>
            </thead>
           <% @order_item.each do |c| %>
            <tbody>
              <tr>
                <td><%=c.item.name%></td>
                <td><%=c.item.with_tax_price %></td>
                <td><%=c.amount%></td>
                <td><%=c.sabtotal%></td>
                <% @total+=c.sabtotal %>
              </tr>
              <% end %>
            </tbody>
          </table>
         </div>
         <div class="col-4">
           <br>商品合計：<%=@total %>
           <br>送料：<%= @order.shipping_fee%>
           <br>請求金額合計：<%= @total + @order.shipping_fee%>
       </div>
    </div>
 </body>
 </html>