config/routes.rb
Rails.application.routes.draw do

    # 顧客用
  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
   devise_for :admin, skip: [:registrations, :passwords], controllers:{
  sessions: "admin/sessions"
   }

  # 顧客のルーティング
  scope module: :public do
    root to: 'homes#top'

    get '/about' =>'homes#about'
    get '/customers/show' =>'customers#show'
    get '/customers/infomation/edit' =>'customers#edit'
    patch '/customers/infomation' =>'customers#update'
    get '/customers/withdraw_check' =>'customers#withdraw_check'
    patch  '/customers/withdraw' =>'customers#withdraw'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/conplete' => 'orders#complete'

    resources :items, only:[:index,:show]
    resources :cart_items, only:[:index,:create,:destroy]
    resources :orders, only:[:index,:show,:new,:create]
  end

   # 管理者側のルーティング設定
  namespace :admin do
  resources :genres ,only:[:create,:update,:edit,:index]
  resources :items , only:[:create,:update,:edit,:index,:new,:show]
  resources :customers , only:[:update,:edit,:index,:show]
  resources :orders , only:[:index,:show]
  end


end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items , dependent: :destroy
  has_many :orders, dependent: :destroy

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + first_name + last_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items , dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_products, dependent: :destroy

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {
    credit: 1, #クレジットカード
    bank: 2, #銀行振込
  }

  has_many :order_products, dependent: :destroy
  belongs_to :customer
   def with_tax_price
    (price * 1.1).floor
   end

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def sabtotal
    (unit_price*1.1).floor * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    # ジャンル一覧の表示
    @genres =Genre.all
  end

  def create
    @genre =Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path

  end

  # 対象ジャンルの編集が押されたときの処理
  def edit
    @genre= Genre.find(params[:id])
  end

  def update
    @genre= Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end



  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    # 商品一覧
    @items=Item.all
  end

  def new
    # 商品新規登録画面
    @item = Item.new
  end

  def create
    # 新規登録の処理
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    # 商品情報の詳細画面
    @item = Item.find(params[:id])
  end

  def edit
    # 商品情報の編集
    @item = Item.find{params[:id]}
  end

  def update
    @item= Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end


  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price,:image,:genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
     <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/0ea1809b33.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header class= "shadow-sm">
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <a class="navbar-brand p-3" href="/"><font color="Black">ロゴ</font></a>
        <div class = "collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
                <!--管理者用のヘッダー-->
                <% if customer_signed_in? %>
                  <li class="nav-item"><%= link_to "マイページ",customers_show_path(current_customer.id) %></li>
                  <li class="nav-item"><%= link_to "商品一覧",items_path%></li>
                  <li class="nav-item"><%= link_to "カート",cart_items_path%></li>
                  <li class="nav-item"><%= link_to "ログアウト",destroy_customer_session_path, method: :delete%></li>
                <% elsif admin_signed_in? %>
                　<li class="nav-item"><%= link_to "商品一覧",admin_items_path%></li>
                  <li class="nav-item"><%= link_to "会員一覧",admin_customers_path%></li>
                  <li class="nav-item"><%= link_to "注文履歴一覧",admin_orders_path%></li>
                  <li class="nav-item"><%= link_to "ジャンル一覧",admin_genres_path%></li>
                  <li class="nav-item"><%= link_to "ログアウト",destroy_admin_session_path, method: :delete%></li>
                <% else %>
                  <li class="nav-item"><%= link_to "About",about_path%></li>
                  <li class="nav-item"><%= link_to "商品一覧",items_path%></li>
                  <li class="nav-item"><%= link_to "新規登録",new_customer_registration_path%></li>
                  <li class="nav-item"><%= link_to "ログイン",new_customer_session_path%></li>
                <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <body>
    <%= yield %>
  </body>
</html>